// 1) შექმენით 20 წყვილი ცვლადი და შინახეთ მათ შიგნით true და false data types სხვადასხვა გზით და გამოიტანთ ეკრაზე მათი შედარება "და" და "ან" ლოგიკუ ოპერატორებით

let a = false;
let b = 100000000 == 9999999999 + 1;
let c = false;
let d = true;
let e = 10000< 10000;
let f = true;
let g = false;
let h = 0 < 100000000;
let i = false;
let j = false;
let k = false;
let l = true;
let m = 10 * 10 == 9 /10;
let n = true;
let o = false;
let p = 9 > 0;
let q = false;
let r = 0 > 9;
let s = false;
let t = false;
let u = 9 < 0;
let v = true;
let w = false;
let x = 0 > 9;
let y = false;
let z = true;
let A = true && false;
let B = true && true;
let C = false;
let D = true;
let E = false;
let F = 2 == 2;
let G = 0 == 2;
let H = 3 < 4;
let I = 1 > 2;
let J = false && false;
let K = true && true;
let L = true && false;
let M = 1 < 3;
let N = 2 > 5;


console.log (a || b);
console.log (c && d);
console.log (e || f);
console.log (g || h);
console.log (i && j);
console.log (k || l);
console.log (m || n);
console.log (o && p);
console.log (q || r);
console.log (s || t);
console.log (u && v);
console.log (w || x);
console.log (y || z);
console.log (A && B);
console.log (C || D);
console.log (E || F);
console.log (G && H);
console.log (I || J);
console.log (K || L);
console.log (M && N);